### ISSUE TITLE
setRange option available ?

### ISSUE THREAD

**Issue by LOG-TAG** [Hariofspades/IncDec#1]
great efforts, Good work !! before trying out this lib I just want to use multiple widgets with integers, depending upon the other widget number , current widget range should be changed.

example: depending on the hotel room selected , set range for the number of adults person range dynamically possible?!!  

currently exploring using this https://github.com/ashik94vc/ElegantNumberButton

update: used this i have to use setArrayList again and again !! I want like set setArrayList once and only change the range or given position to end position will be grateful

**Comment by Hariofspades** [comment]
@LOG-TAG Will modify and let you know. Thanks for the feedback :)

**Comment by Hariofspades** [comment]
@LOG-TAG I have provided the range feature. You can set Arraylist in one method and provide startIndex, stopIndex and interval in another method. Please let me know if this is what you asked for.
I've also updated the documentation

```java
ArrayList<String> values=new ArrayList<>();
        values.add("Apple");
        values.add("Ball");
        values.add("Cat");
        values.add("Dog");
        values.add("Elephant");

 IncDecCircular incdec=(IncDecCircular)findViewById(R.id.incdec);
 incdec.setConfiguration(LinearLayout.HORIZONTAL,IncDecCircular.TYPE_ARRAY,
                IncDecCircular.DECREMENT,IncDecCircular.INCREMENT);
 incdec.setArrayList(values); //set Arraylist
 incdec.setArrayIndexes(1,3,1); //startIndex, stopIndex, interval
 incdec.enableLongPress(true,true,500);
```

**Comment by LOG-TAG** [comment]
awesome thanks!

P.S: I'm trying to alter the Textview with https://github.com/adnan-SM/TimelyTextView :)

**Comment by Hariofspades** [comment]
Good one. All the best :)
