### ISSUE TITLE
How to Remove the BG for IncDecImageButton ?

### ISSUE THREAD

**Issue by AruLNadhaN** [Hariofspades/IncDec#2]
I need to create a picker like this [one.](http://i.imgur.com/PDZz7Js.png)

I tried using the `IncDecImageButton`. But I can't remove the background of the Image Button as like the Native Image Button.

**Comment by Hariofspades** [comment]
Hi @AruLNadhaN ,

Thanks for bring this to my notice. Can you please provide me the drawable (xml) for the ImageButton - which you're trying to accomplish (just for testing)??

**Comment by AruLNadhaN** [comment]
I used the same like the sample code 

<com.hariofspades.incdeclibrary.IncDecImageButton
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:textSizeB="24"
        android:id="@+id/incdec"
        android:layout_marginTop="20dp"
        app:textColorB="@color/white"
        app:leftButtonColorTintB="@color/colorPrimaryDark"
        app:rightButtonColorTinitB="@color/colorPrimary"
        app:leftDrawableTintB="@color/white"
        app:rightDrawableTintB="@color/white"
        app:leftDrawableB="@drawable/ic_remove_black_24dp"
        app:rightDrawableB="@drawable/ic_add_black_24dp"/>

**Comment by Hariofspades** [comment]
Hi @AruLNadhaN 

I've fixed it. By default, the background will be transparent and if you add tintcolors, you can see the backgroud. You can also set left and right backgroud as drawable via xml and java
```xml
 app:leftBackground="@drawable/round"
 app:rightBackground="@drawable/round"
```
```java
incdecImg2.setBackground(ContextCompat.getDrawable(this,R.drawable.round),
                    ContextCompat.getDrawable(this,R.drawable.round));
```
Please let me know if this is what you seek.

**Comment by AruLNadhaN** [comment]
I cleaned & rebuild my project. But the latest changes are not reflected in my build folder code. Maybe you should change the version in gradle or something!

`Error:(87) No resource identifier found for attribute 'leftBackground' in package`

**Comment by Hariofspades** [comment]
sorry, did not update the documentation. It's updated.
```groovy
compile 'com.hariofspades.IncDec:incdeclibrary:0.0.2'
```
for xml
```xml
app:leftBackgroundB="@drawable/round"
app:rightBackgroudnB="@drawable/round"
```
for java
```java
 incdecImg2.setBackgroundforButton(ContextCompat.getDrawable(this,R.drawable.round),
                ContextCompat.getDrawable(this,R.drawable.round));
```

**Comment by AruLNadhaN** [comment]
Thanks!. But I have an Issue with the Initial value. I'm trying to set it as 1. But it starts only from 0.

            `mPicker.setConfiguration(LinearLayout.HORIZONTAL,IncDecImageButton.TYPE_INTEGER,
                    IncDecImageButton.DECREMENT,IncDecImageButton.INCREMENT);
            mPicker.setupValues(1,20,1,1);
            mPicker.enableLongPress(true,true,200);`

**Comment by Hariofspades** [comment]
Oops. That's not working only for integer types. 
Have Fixed it. Please try

```groovy
compile 'com.hariofspades.IncDec:incdeclibrary:0.0.3'
```

**Comment by AruLNadhaN** [comment]
The values are being changed due to RV Recycling. Do u have a way to solve this ?

**Comment by Hariofspades** [comment]
RecyclerView will always recycle and bring things back to initial stage. You need to maintain the new value (changed value) as flag and set the value back in onBind. That's the one way I know. I faced similar problem in keeping the checkBox component alive in RecyclerView. Flag is one solution

Also I've heard you can stop RecyclerView recycling  (onbind - setrecycleable to false)  if your list is small - not suggestible* but a workaround.

Not suggestible* - bcoz, if you're not recycling, then it is better to go with ListView itself rather than RecyclerView

**Comment by AruLNadhaN** [comment]
Thanks! I have already used the Flag solution. Do we have any method like `setvalue` So that i can set the value back in onBind!

**Comment by Hariofspades** [comment]
Yes. You have function setValue. you can use it to set values for integer and float items.
Please try and let me know if that is working as expected.
```java
incdec.setValue(3);
```
